# Generated by Django 4.2 on 2025-04-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HexGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board", models.JSONField(default=list)),
                ("player_turn", models.CharField(default="human", max_length=10)),
                ("last_moves", models.JSONField(default=list)),
                ("moves_history", models.JSONField(default=list)),
                ("winner", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("human_color", models.CharField(default="red", max_length=10)),
                ("win_probability", models.JSONField(default=dict)),
                (
                    "mode",
                    models.CharField(
                        choices=[("HUMAN_AI", "Human vs AI"), ("AI_AI", "AI vs AI")],
                        default="HUMAN_AI",
                        max_length=10,
                    ),
                ),
                (
                    "current_ai_player",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
    ]
