# Generated by Django 4.2 on 2025-04-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hexgame", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hexgame",
            old_name="human_color",
            new_name="player_color",
        ),
        migrations.AlterField(
            model_name="hexgame",
            name="winner",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
