# Generated by Django 4.2 on 2025-04-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hexgame", "0002_rename_human_color_hexgame_player_color_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hexgame",
            old_name="player_color",
            new_name="human_color",
        ),
    ]
