# Generated by Django 4.2 on 2025-04-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hexgame", "0003_rename_player_color_hexgame_human_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hexgame",
            name="current_ai_player",
        ),
    ]
